import{Food} from  './app/shared/models/food';

export const sample_foods: Food[] = [
    {
        id: '1',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['Italy'],
        rating: 4.0,
        imageUrl: "food_1.jpg",
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Burger',
        price: 5,
        cookTime: '40-50',
        favorite: false,
        origins: ['Germany'],
        rating: 4.0,
        imageUrl: 'food_2.jpg',
        tags: ['FastFood', 'Burger', 'Lunch'],
    },
    {
        id: '3',
        name: 'Pasta',
        price: 7,
        cookTime: '20-30',
        favorite: true,
        origins: ['Italy'],
        rating: 4.5,
        imageUrl: 'food_3.jpg',
        tags: ['FastFood', 'Pasta', 'Dinner'],
    },
    {
        id: '4',
        name: 'Sushi',
        price: 12,
        cookTime: '50-60',
        favorite: true,
        origins: ['Japan'],
        rating: 5.0,
        imageUrl: 'food_4.jpg',
        tags: ['Seafood', 'Sushi', 'Lunch'],
    },
    {
        id: '5',
        name: 'Salad',
        price: 6,
        cookTime: '10-15',
        favorite: false,
        origins: ['Global'],
        rating: 4.2,
        imageUrl: 'food_5.jpg',
        tags: ['Healthy', 'Salad', 'Dinner'],
    },
    {
        id: '6',
        name: 'Ice Cream',
        price: 3,
        cookTime: '5-10',
        favorite: true,
        origins: ['Global'],
        rating: 4.8,
        imageUrl: 'food_6.jpg',
        tags: ['Dessert', 'IceCream', 'Snack'],
    }
];

